# Generated by Django 5.0 on 2023-12-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationdenicoetalix', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
