# Generated by Django 5.0 on 2024-01-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationdenicoetalix', '0005_remove_categoriedesoumission_date_limite_de_correction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriedesoumission',
            name='date_limite_de_correction_avant_conference',
            field=models.IntegerField(db_column='Date_limite_de_correction_avant_conference'),
        ),
    ]
