# Generated by Django 5.0 on 2024-01-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationdenicoetalix', '0007_rename_date_de_notification_categoriedesoumission_délai_de_notification_après_soummission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriedesoumission',
            name='délai_de_notification_après_soummission',
            field=models.IntegerField(db_column='Delai_de_notification'),
        ),
    ]
