# Generated by Django 5.0 on 2024-01-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationdenicoetalix', '0008_alter_categoriedesoumission_délai_de_notification_après_soummission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soumission',
            name='utilisateur',
        ),
    ]
