# Generated by Django 5.0 on 2024-01-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationdenicoetalix', '0009_remove_soumission_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriedesoumission',
            old_name='délai_de_notification_après_soummission',
            new_name='delai_de_notification_apres_soummission',
        ),
    ]
